---
name: VCfs
version: v0.0.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: Version Control agnostic interface on the local system
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=VCfs
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://svn.scratchcomputing.com/VCfs/trunk
requires:
  Class::Accessor::Classy: v0.1.3
  IPC::Run: 0.8
build_requires:
  Module::Build: 0.2808
  Test::More: 0.72
provides:
  VCfs:
    file: lib/VCfs.pm
    version: v0.0.1
generated_by: Module::Build version 0.3103
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
